export const ADD_INGREDIENT: 'ADD_INGREDIENT'  = 'ADD_INGREDIENT';
export const ADD_BUN: 'ADD_BUN' = 'ADD_BUN';
export const RESET_CONSTRUCTOR: 'RESET_CONSTRUCTOR' = 'RESET_CONSTRUCTOR';
export const SET_INGREDIENTS: 'SET_INGREDIENTS' = 'SET_INGREDIENTS';
export const PLACE_ORDER_START: 'PLACE_ORDER_START' = 'PLACE_ORDER_START';
export const PLACE_ORDER_SUCCESS: 'PLACE_ORDER_SUCCESS' = 'PLACE_ORDER_SUCCESS';
export const PLACE_ORDER_FAIL: 'PLACE_ORDER_FAIL' = 'PLACE_ORDER_FAIL';
export const REMOVE_INGREDIENT: 'REMOVE_INGREDIENT' = 'REMOVE_INGREDIENT';
export const SORT_INGREDIENTS: "SORT_INGREDIENTS" = "SORT_INGREDIENTS";

export const RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST' = 'RESET_PASSWORD_REQUEST';
export const PASSWORD_REQUEST_SUCCES: 'PASSWORD_REQUEST_SUCCES' = 'PASSWORD_REQUEST_SUCCES';
export const PASSWORD_REQUEST_FAILURE: 'PASSWORD_REQUEST_FAILURE' = 'PASSWORD_REQUEST_FAILURE';

export const RESET_PASSWORD_SUCCES: "RESET_PASSWORD_SUCCES" = "RESET_PASSWORD_SUCCES";
export const RESET_PASSWORD_FAILURE: "RESET_PASSWORD_FAILURE" = "RESET_PASSWORD_FAILURE";
export const RESET_PASSWORD_BEGIN: "RESET_PASSWORD_BEGIN" = "RESET_PASSWORD_BEGIN";

export const REGISTER_REQUEST: "REGISTER_REQUEST" = "REGISTER_REQUEST";
export const REGISTER_SUCCESS: "REGISTER_SUCCESS" = "REGISTER_SUCCESS";
export const REGISTER_FAILURE: "REGISTER_FAILURE" = "REGISTER_FAILURE";

export const LOGIN_REQUEST: "LOGIN_REQUEST" = "LOGIN_REQUEST";
export const LOGIN_SUCCESS: "LOGIN_SUCCESS" = "LOGIN_SUCCESS";
export const LOGIN_FAILURE: "LOGIN_FAILURE" = "LOGIN_FAILURE";

export const LOGOUT_REQUEST: "LOGOUT_REQUEST" = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS: "LOGOUT_SUCCESS" = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE: "LOGOUT_FAILURE" = "LOGOUT_FAILURE";

export const UPDATE_USER_REQUEST: "UPDATE_USER_REQUEST" = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS" = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE: "UPDATE_USER_FAILURE" = "UPDATE_USER_FAILURE";

export const AUTH_CHECK_COMPLETE: "AUTH_CHECK_COMPLETE" = "AUTH_CHECK_COMPLETE";

export const CLOSE_MODAL: "CLOSE_MODAL" = "CLOSE_MODAL";
export const OPEN_MODAL: "OPEN_MODAL" = "OPEN_MODAL";

export const OPEN_WS_CONNECTION: "OPEN_WS_CONNECTION" = "OPEN_WS_CONNECTION";
export const CLOSE_WS_CONNECTION: "CLOSE_WS_CONNECTION" = "CLOSE_WS_CONNECTION";
export const UPDATE_ORDERS: "UPDATE_ORDERS" = "UPDATE_ORDERS";

export const SET_CURRENT_ORDER: "SET_CURRENT_ORDER" = "SET_CURRENT_ORDER";
export const FETCH_ORDER_DETAILS_SUCCESS: 'FETCH_ORDER_DETAILS_SUCCESS' = 'FETCH_ORDER_DETAILS_SUCCESS';

export const WS_CONNECTION_SUCCESS: "WS_CONNECTION_SUCCESS" = "WS_CONNECTION_SUCCESS";
export const WS_CONNECTION_ERROR: "WS_CONNECTION_ERROR" = "WS_CONNECTION_ERROR";
export const WS_CONNECTION_CLOSED: "WS_CONNECTION_CLOSED" = "WS_CONNECTION_CLOSED";

export const OPEN_USER_WS_CONNECTION: 'OPEN_USER_WS_CONNECTION' = 'OPEN_USER_WS_CONNECTION';
export const CLOSE_USER_WS_CONNECTION: 'CLOSE_USER_WS_CONNECTION' = 'CLOSE_USER_WS_CONNECTION';
export const USER_WS_CONNECTION_SUCCESS: "USER_WS_CONNECTION_SUCCESS" = "USER_WS_CONNECTION_SUCCESS";
export const USER_WS_CONNECTION_ERROR: "USER_WS_CONNECTION_ERROR" = "USER_WS_CONNECTION_ERROR";
export const USER_WS_CONNECTION_CLOSED: "USER_WS_CONNECTION_CLOSED" = "USER_WS_CONNECTION_CLOSED";
export const UPDATE_USER_ORDERS: "UPDATE_USER_ORDERS" = "UPDATE_USER_ORDERS";
